Features/lab2
lsd-maddrive/ROS_course pull request #20
Opened 2023-02-21 19:07 UTC by lasauveetgarde

Добавлена вторая лабка

2023-02-23 09:13 UTC, KaiL4eK requested changes

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +Начнем, чтобы что-то запустить нужно воспользоваться утилитой запуска узла `rosrun`, которая имеет следующее описание:
зпт

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +Начнем, чтобы что-то запустить нужно воспользоваться утилитой запуска узла `rosrun`, которая имеет следующее описание:
, нужно

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +`roscore`
давайте выделять это в блоки кода, а не inline код, чтобы было более явно выделено
посмотрите первую лабу

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +<img src="../assets/lab2_SHIFU.png" width=300>
чтобы не делать префикс лаб, предлагаю реорганизовать assets именно для лаб по папкам, lab1 и т.д.

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +Вот и подошел черед познакомиться с первыми базовыми вещами ROS - __узлами__. Под узлом подразумевается программа, которая производит некоторые действия. Узлы соединяются __топиками__, через которые
Почему выделено подчеркиванием? Давайте введем файлик с единым форматом? Есть https://github.com/lsd-maddrive/ROS_course/blob/main/resources/template.md, там можно зафиксировать, что через ** обозначаем термины, 💪 - это задачка, ❔ - справка, ⚠️ - предупреждение, ✅ - заметка (обычно с термином)

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +Вот и подошел черед познакомиться с первыми базовыми вещами ROS - __узлами__. Под узлом подразумевается программа, которая производит некоторые действия. Узлы соединяются __топиками__, через которые
В https://github.com/lsd-maddrive/ROS_course/blob/main/topics/0_02_Git_CLI.md все это использовалось, предлагаю опираться на общий формат

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +`rosrun rospy_tutorials talker __name:=talker`
Может тут убрать? Таки ренейминг еще не рассматривался

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> Запустите указанные утилиты. Не забывайте про то, что каждая утилита (узлы и мастер) при запуске бесконечно работают, поэтому запуск производится в отдельных терминалах.
Не забывайте про то, что если узел при запуске работает бесконечно, то для запуска другого узла нужен новый терминал

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +#!/usr/bin/env python
python3

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> Строка `#!/usr/bin/env python` необходима для запуска, она сообщает системе о том, что данный файл необходимо запускать через интерпретатор `python`.
кажется, что это можно убрать, в первой лабе писали скрипт

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +# Какие-то узлы и топики  :knot: :tshirt:
knot не рендерится на GH

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> :brain: Найдите в справке утилиты `rostopic` аргумент измерения частоты публикации и измерьте частоту публикации в топик `/chatter`
Можно эту иконку тоже как иконку для задач добавить

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> :mechanical_arm:	Включите `rqt_graph` и в группе `Hide` снимите галочку с `Debug`. Убедитесь в том, что представлены все узлы и топики (даже с отладкой) системы, с помощью утилит `rosnode` и `rosto
И вот эту)

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +__Пространство имен__ - фактически, это префикс имени узла в системе. Концептуально, пространство имен объединяет несколько узлов по определенной задаче, расположению или другому признаку. Задавая пр
Вот здесь, кажется, можно добавить иконку термина

2023-02-23 09:13 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> :mechanical_arm: На основании предыдщуей задачи дополните программу: при достижении числа 100 отправляйте сообщение в новый топик и сбрасывайте счетчик. Также необходимо создать новый узел с подпис
предыдущей

2023-02-24 22:24 UTC, Alakeyska commented on labs/02_Nodes_topics.md
> +Вот и подошел черед познакомиться с первыми базовыми вещами ROS - __узлами__. Под узлом подразумевается программа, которая производит некоторые действия. Узлы соединяются __топиками__, через которые
Зафиксировано

2023-02-25 22:39 UTC, KaiL4eK requested changes
Еще пара мелких замечаний/вопросов

2023-02-25 22:39 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +#!/usr/bin/env python
Пропущено python3

2023-02-25 22:39 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> Проверьте возможные команды утилиты `rosmsg`
Значок задачки пропущен?

2023-02-25 22:39 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> :mechanical_arm:	Запустите узел пакета `rospy_tutorials` с именем `talker` и присвойте такое же имя `__name:=talker`. Убедитесь, что первый `talker` закрылся с сообщением о перехвате (`shutdown req
После значка разве табуляция? Может достаточно пробела?

2023-02-25 22:39 UTC, KaiL4eK commented on resources/template.md
> +> ⚠️  - Предупреждение
Лишний пробел?

2023-02-25 22:39 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +
Слишком много пробелов?

2023-02-25 22:39 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> Запустите узлы утилиты. Не забывайте про то, что если узел при запуске работает бесконечно, то для запуска другого узла нужен новый терминал.
Задачка?

2023-02-25 22:39 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> В любой экосистеме ROS существует мастер (и он единственный), который работает с узлами. Фактически, он полностью организует их.
Заметка?

2023-02-25 22:39 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> Проверьте возможные команды утилиты `rosnode`
Задачка

2023-02-25 22:39 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> Проверьте возможные команды утилиты `rostopic`
Задачка?

2023-02-25 22:39 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +# В данном случае достаточно спина, по факту замена `rospy.is_shutdown()`
В данном случае достаточно спина, по факту замена `while rospy.is_shutdown()`

2023-02-25 22:39 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +> Знак '`:=`' означает присваивание и будет далее часто использоваться при мапировании, установки значений:baby_chick:.
Заметка

2023-02-25 22:41 UTC, KaiL4eK commented on resources/template.md
> +## Содержание
Предлагаю написать, с помощью какого extension авто-генерится содержание

2023-02-25 23:41 UTC, Alakeyska commented on resources/template.md
> +## Содержание
Кстати, с помощью какого?

2023-02-25 23:53 UTC, Alakeyska commented on labs/02_Nodes_topics.md
> +> :mechanical_arm:	Запустите узел пакета `rospy_tutorials` с именем `talker` и присвойте такое же имя `__name:=talker`. Убедитесь, что первый `talker` закрылся с сообщением о перехвате (`shutdown req
Вообще здесь пробел стоит. Это уже гитхаб походу странно diff отображает

2023-02-25 23:56 UTC, Alakeyska commented on labs/02_Nodes_topics.md
> +> Проверьте возможные команды утилиты `rosmsg`
Здесь мозги наверное 🧠

2023-02-26 01:11 UTC, Alakeyska commented
Добавил инфу про авто-оглавления в template.md. Ещё не понятно как быть с первым уровням раздела, который под #. В данный момент этот уровень у нас использовался только в самом заголовке топиков, а сейчас в лабе2 он используются для отделения глав лабы. Может в таком случае использовать главный раздел # не только для первого предложения в файле?

2023-02-27 11:03 UTC, KaiL4eK reviewed
Последний заход))

2023-02-27 11:03 UTC, KaiL4eK commented on resources/template.md
> +# Раздел
Уровень 1 - титул топика/лабы
Уровень 2 - раздел
Уровень 3 - подраздел

2023-02-27 11:03 UTC, KaiL4eK commented on labs/02_Nodes_topics.md
> +# ROS узлы и топики
Поправьте заголовки + удалите плз из _planned папки файл второй лабы

2023-02-27 11:05 UTC, KaiL4eK commented on resources/template.md
> +Для автогенерации содержания, выполните команду `Create Table of Contents` в палитре комманд VS code (`Ctrl+Shift+P`).
команд

2023-02-27 11:05 UTC, KaiL4eK commented on resources/template.md
> +Для автогенерации содержания, выполните команду `Create Table of Contents` в палитре комманд VS code (`Ctrl+Shift+P`).
дабл "м" - этоангл вариант

2023-02-27 16:10 UTC, KaiL4eK approved these changes

2023-02-28 15:39 UTC, merged