Added some useful links
lsd-maddrive/ROS_course pull request #23
Opened 2023-03-05 13:36 UTC by kostyk348

Добавил несколько полезных ссылок на различный линуксовский софт и пару гайдов по гиту и командной строке (а то ссылки в дискорде я думаю чекают далеко не многие :) )

2023-03-05 16:30 UTC, KaiL4eK requested changes

2023-03-05 16:30 UTC, KaiL4eK commented on UsefulLinks/Полезные ссылки и руководства.md
> +1. https://github.com/benthayer/git-gud - Довольно подробный и полезный туториал по git
На данный момент получается так, что всего один файл и по названию не кажется, что он будет расширяться. Пока не видно больших объемов, лучше не создавать новых файлов. Предлагаю поменять расположение ссылок. Есть два варианта:
- Добавить ссылки прямо в README.md отдельным разделом
- Добавить ссылки прямо в соответствующие топики (более предпочтительный)

2023-03-05 18:38 UTC, Alakeyska commented on UsefulLinks/Полезные ссылки и руководства.md
> +1. https://github.com/benthayer/git-gud - Довольно подробный и полезный туториал по git
Согласен со вторым вариантом. Таким образом информация будет более структурированной, чем набор ссылок подряд. Если хочешь инфу по гиту - заходи в топик по гиту и т.д =).

2023-03-05 18:49 UTC, kostyk348 commented on UsefulLinks/Полезные ссылки и руководства.md
> +1. https://github.com/benthayer/git-gud - Довольно подробный и полезный туториал по git
Хмм, т.е. разбить на несколько файлов чисто по темам?

2023-03-05 18:51 UTC, kostyk348 commented on UsefulLinks/Полезные ссылки и руководства.md
> +1. https://github.com/benthayer/git-gud - Довольно подробный и полезный туториал по git
И дополнить какими-нибудь небольшими вещами по типу кратеньких гайдов или советов

2023-03-05 18:52 UTC, Alakeyska commented on UsefulLinks/Полезные ссылки и руководства.md
> +1. https://github.com/benthayer/git-gud - Довольно подробный и полезный туториал по git
В конце каждой лабы/топика есть раздел "Полезные ресурсы", можно туда. Файлы не нужно плодить.

2023-03-05 18:53 UTC, kostyk348 commented on UsefulLinks/Полезные ссылки и руководства.md
> +1. https://github.com/benthayer/git-gud - Довольно подробный и полезный туториал по git
Понял тогда посмотрю куда это можно определить

2023-03-05 19:29 UTC, kostyk348 commented on UsefulLinks/Полезные ссылки и руководства.md
> +1. https://github.com/benthayer/git-gud - Довольно подробный и полезный туториал по git
Добавил ссылки в уже существующие топики и убрал ту папку

2023-03-05 20:43 UTC, Alakeyska commented on topics/0_01_Shell.md
> +### Vim/NeoVim
Хорошо. Добавь только в содержание, пожалуйста

2023-03-05 20:45 UTC, Alakeyska commented on topics/0_02_Git_CLI.md
> +``# Git - основы
Что-то пошло не так)

2023-03-06 04:47 UTC, kostyk348 commented on topics/0_01_Shell.md
> +### Vim/NeoVim
Добавил в содержание

2023-03-06 04:48 UTC, kostyk348 commented on topics/0_02_Git_CLI.md
> +``# Git - основы
Ошибки пофиксил, лишнее убрал

2023-03-06 07:24 UTC, Alakeyska commented
Еще нужно поменять ветку на develop. Все изменения сначала вливаем в develop, а потом только в main.

2023-03-06 08:17 UTC, kostyk348 commented
Ветку поменял, еще случайно запушил сюда файлы для другого репозитория но уже стер их, так что теперь все ок должно быть

2023-03-06 08:24 UTC, closed without merging